spring.application.name=IFCD0014_2026_06_bibliotecavideojuegos

# server.port=8085 # Por defecto vamos al 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/db_videojuegos
spring.datasource.username=fpaniagua
spring.datasource.password=patata71
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.zaxxer.hikari=DEBUG

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5


